#!/usr/bin/env python3
import os
import sys

filedir = os.path.dirname(__file__)
path = os.path.join(filedir, '..')
path = os.path.abspath(path)

sys.path.insert(0, path)
from codegen import codegen_main

sys.exit(codegen_main.codegen_main())
